wandb_version: 1

BS:
  desc: null
  value: 32
DATA_DIR:
  desc: null
  value: ../data/imagenette2-160
DEVICE:
  desc: null
  value: cuda
EPOCHS:
  desc: null
  value: 10
IMG_SIZE:
  desc: null
  value: 160
MODEL:
  desc: null
  value: efficientnet_b0
TEST_AUG:
  desc: null
  value: "Compose([\n  Resize(always_apply=True, p=1, height=160, width=160, interpolation=1),\n\
    \  Normalize(always_apply=False, p=1.0, mean=(0.485, 0.456, 0.406), std=(0.229,\
    \ 0.224, 0.225), max_pixel_value=255.0),\n], p=1.0, bbox_params=None, keypoint_params=None,\
    \ additional_targets={})"
TEST_DATA_DIR:
  desc: null
  value: ../data/imagenette2-160/val
TRAIN_AUG:
  desc: null
  value: "Compose([\n  Resize(always_apply=True, p=1, height=160, width=160, interpolation=1),\n\
    \  HorizontalFlip(always_apply=False, p=0.5),\n  VerticalFlip(always_apply=False,\
    \ p=0.5),\n  Rotate(always_apply=False, p=0.8, limit=(-120, 120), interpolation=1,\
    \ border_mode=4, value=None, mask_value=None),\n  RandomBrightness(always_apply=False,\
    \ p=0.5, limit=(0.09, 0.6)),\n  Normalize(always_apply=False, p=1.0, mean=(0.485,\
    \ 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0),\n], p=1.0,\
    \ bbox_params=None, keypoint_params=None, additional_targets={})"
TRAIN_DATA_DIR:
  desc: null
  value: ../data/imagenette2-160/train
_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.10
      5: 0.10.27
      8:
      - 5
