wandb_version: 1

BS:
  desc: null
  value: 32
DATA_DIR:
  desc: null
  value: ../data/imagenette2-160
DEVICE:
  desc: null
  value: cuda
EPOCHS:
  desc: null
  value: 10
IMG_SIZE:
  desc: null
  value: 160
MODEL:
  desc: null
  value: efficientnet_b0
TEST_AUG:
  desc: null
  value: "Compose(\n    CenterCrop(size=(160, 160))\n    ToTensor()\n    Normalize(mean=(0.485,\
    \ 0.456, 0.406), std=(0.229, 0.224, 0.225))\n)"
TEST_DATA_DIR:
  desc: null
  value: ../data/imagenette2-160/val
TRAIN_AUG:
  desc: null
  value: "Compose(\n    RandomCrop(size=(160, 160), padding=None)\n    RandomHorizontalFlip(p=0.5)\n\
    \    ToTensor()\n    Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224,\
    \ 0.225))\n)"
TRAIN_DATA_DIR:
  desc: null
  value: ../data/imagenette2-160/train
_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.10
      5: 0.10.27
      8:
      - 5
